### PR TITLE
Upgrade to 3.26.1

### PR DESCRIPTION
**Pull request by bochecha**

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Looks good, I'll also fix the appdata issue in gnome-calendar upstream too.

**Comment by GeorgesStavracas** [comment]
Actually, I think this manifest is missing the Logind DBus permission. This is also an issue with upstream, so would be nice to fix that there too.

**Comment by bochecha** [comment]
I've opened https://bugzilla.gnome.org/show_bug.cgi?id=788469 for upstream patches.

**Comment by GeorgesStavracas** [comment]
Looks good, thanks!

**Pull request merged**
