### PR TITLE
Update to 3.32.0

### PR DESCRIPTION
**Pull request by bochecha**
This updates GNOME Calendar and its dependencies to their latest version.

---

Please note that I had to use the Github web UI to make this change because my computer broke recently and as a result I have nowhere to test this.

Like every change, it would be best to test this properly before merging it. If you'd prefer me to test this, I should be able to do it in a week or two.

If someone can test it before then, please do. :slightly_smiling_face:

### CODE REVIEW

**Comment by bochecha** [comment]
```
FB: Running: flatpak build --die-with-parent --nofilesystem=host /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/rofiles/rofiles-oMaoc3 appstream-compose --prefix=/app --origin=flatpak --basename=org.gnome.Calendar org.gnome.Calendar
Processing application org.gnome.Calendar
org.gnome.Calendar.desktop:        AppData problem: attribute-invalid : <release> timestamp is in the future
Error loading AppData file: AppData file /app/share/appdata/org.gnome.Calendar.appdata.xml was not valid
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

Hmmm, that's weird…

**Comment by bochecha** [comment]
Ok, that's https://gitlab.gnome.org/GNOME/gnome-calendar/commit/fa19ac27f51436ebacd0e9f3fbe27b9520c28fed

I guess we need to wait for 3.32.1 then. :slightly_smiling_face:

**Comment by GeorgesStavracas** [comment]
I'm a terrible person and managed to screw up every single thing:

 * Released 3.32.1 and updated directly into master
 * Completely missed your MR
 * Broke the build at least 5 times
 * Avoided test builds

Sorry :(

**Comment by bochecha** [comment]
> I'm a terrible person

No you're not. :slightly_smiling_face: 

> and managed to screw up every single thing

It happens. Thanks for updating Calendar!

**Pull request closed without merging**
